language: node_js
node_js:
  - 10.8.0
before_install:
  - rvm install 2.4.1
install:
  - bundle install
script:
  - jekyll build
deploy:
  provider: script
  script: 
    - bash ./.scripts/update.sh
    - bash ./.scripts/deploy.sh
  on:
    branch: master
