name: James Fenn
description: James Fenn's portfolio site.
url: https://jfenn.me
baseurl: "/"

collections:
    types:
        output: false
    links:
        output: true
    people:
        output: false
    orgs:
        output: false
    projects:
        output: true
    blogs:
        output: true
        permalink: /blog/:year-:month-:day-:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts

plugins:
  - jekyll-sitemap
