name: James Fenn
author: James Fenn
description: James Fenn's portfolio site.
icon: "/images/me.jpg"
image: "/images/headers/snowytrees.jpg"

url: "/"
baseurl: "/"

collections:
    types:
        output: false
    links:
        output: true
    people:
        output: false
    orgs:
        output: false
    projects:
        output: true
        permalink: /projects/:title/
    blogs:
        output: true
        permalink: /blog/:year-:month-:day-:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
