name: James Fenn
author: James Fenn
email: "me@jfenn.me"
bio: "Enjoys writing software on loud keyboards. Starts too many projects. Consumes food."
description: "Writer of bad puns and slightly better software. This website contains information about my adventures in programming, current projects, and me."
icon: "/images/me.jpg"
image: "/images/headers/snowytrees.jpg"

contact:
  - name: "Discord"
    icon: "group"
    url: "https://discord.jfenn.me/"
  - name: "Telegram"
    icon: "chat"
    url: "https://t.me/joinchat/JV--FRZrSf-NJqeE0OGKXg"
  - name: "Matrix"
    icon: "chat"
    url: "https://matrix.to/#/!apQumaWwHIRDmTIYAr:matrix.org"

url: "https://jfenn.me"
domainurl: "https://jfenn.me"
baseurl: "/"

collections:
    types:
        output: false
    links:
        output: true
    people:
        output: false
    orgs:
        output: false
    projects:
        output: true
        permalink: /projects/:title/
    blogs:
        output: true
        permalink: /blog/:year-:month-:day-:title/
    tags:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
